// version checking pipeline
pipeline {
    agent any
    stages {
        stage('git version checking') {
            steps {
                sh 'git version'
            }
        }
        stage('ansible version checking') {
            steps {
                sh 'ansible --version'
            }
        }
        stage('docker version checking') {
            steps {
                sh 'docker version'
            }
        }
        stage('terraform version checking') {
            steps {
                sh 'terraform version'
            }
        }
    }
}

// infra setup pileline
pipeline {
    agent any
    environment {
        cred = credentials('aws-key')
        TF_WORKDIR = 'devops'  // Path where your main.tf is located
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Muhilan25/udemy-test-project.git']])
            }
        }

        stage('Terraform Init') {
            steps {
                dir("${TF_WORKDIR}") {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                dir("${TF_WORKDIR}") {
                    sh 'terraform plan'
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                dir("${TF_WORKDIR}") {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}

// Ansible install
pipeline {
    agent any 
    environment {
        privatekey = credentials('ansiblekey')
    }
    stages {
        stage('checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Muhilan25/udemy-project1.git']])  
            }
        }
        stage('ansible test') {
            steps {
                sh "ansible all -i inventory -m ping --private-key ${privatekey}"
                sh "ansible-playbook -i inventory --private-key ${privatekey} playbook.yaml"
            }
        }
    }
}