// version checking pipeline
pipeline {
    agent any
    stages {
        stage('git version checking') {
            steps {
                sh 'git version'
            }
        }
        stage('ansible version checking') {
            steps {
                sh 'ansible --version'
            }
        }
        stage('docker version checking') {
            steps {
                sh 'docker version'
            }
        }
        stage('terraform version checking') {
            steps {
                sh 'terraform version'
            }
        }
    }
}

// infra setup pileline
pipeline {
    agent any
    environment {
        cred = credentials('aws-key')
    }
    stages {
        stage('checkout') {
            steps {
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Muhilan25/udemy-test-project.git']])
            }
        }
        stage('terraform init') {
            steps {
                sh 'terraform init'
            }
        }
        stage('terraform plan') {
            steps {
                sh 'terraform plan'
            }
        }
        stage('terraform apply') {
            steps {
                sh 'terraform apply -auto-approve'
            }
        }
    }
}